name: Build and Deploy .NET 7 to FreeASPHosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup .NET 7 SDK
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      # 3️⃣ Restore dependencies
      - name: Restore dependencies
        working-directory: ./LubanziChillDropApi
        run: dotnet restore

      # 4️⃣ Build project
      - name: Build project
        working-directory: ./LubanziChillDropApi
        run: dotnet build --configuration Release

      # 5️⃣ Publish the app
      - name: Publish project
        working-directory: ./LubanziChillDropApi
        run: dotnet publish -c Release -o ./publish

      # 6️⃣ Deploy to FreeASPHosting via FTP
      - name: Deploy via SFTP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          source: "./publish/*"
          target: "/site/wwwroot"


      # 7️⃣ Verify deployment
      - name: Verify deployment
        run: |
          echo "Checking deployment status..."
          curl -I http://${{ secrets.SFTP_HOST }}/site/wwwroot
          echo "Deployment verified."
