name: Deploy ChillDrop API

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t philane07/lubanzi-chilldrop:latest -f LubanziChillDropApi/Dockerfile ./LubanziChillDropApi
        docker push philane07/lubanzi-chilldrop:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Restart Kubernetes deployment
      run: |
         kubectl config use-context docker-desktop
         kubectl set image deployment/chilldrop-api chilldrop-api=philane07/lubanzi-chilldrop:latest -n chilldrop || kubectl set image deployment/chilldrop-api chilldrop-api=philane07/lubanzi-chilldrop:latest
         kubectl rollout status deployment/chilldrop-api -n chilldrop || kubectl rollout status deployment/chilldrop-api